export const keys = {
    en: [
        [
            { key: 'Q', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'W', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'E', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'R', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'T', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'Y', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'U', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'I', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'O', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'P', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
        ],
        [
            { key: 'A', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'S', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'D', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'F', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'G', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'H', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'J', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'K', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'L', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
        ],
        [
            { key: '^', moreSymbol: [], sound: 'keyException.mp3', style: 'keyException', isException: true, exeptionStyle: { width: 42, marginRight: 9 } },
            { key: 'Z', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'X', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'C', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'V', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'B', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'N', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'M', moreSymbol: [], sound: 'keyCommon.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'Delete', moreSymbol: [], sound: 'keyException.mp3', style: 'keyException', isException: true, exeptionStyle: { width: 42, marginLeft: 9 } },
        ],
        [
            { key: '123', moreSymbol: [], sound: 'keyException.mp3', style: 'keyException', isException: true, exeptionStyle: { width: 35 } },
            { key: 'space', moreSymbol: [], sound: 'keyException.mp3', style: 'keyException', isException: true, exeptionStyle: { width: '40%', backgroundColor: '#fff' } },
            { key: '.', moreSymbol: [','], sound: 'keyException.mp3', style: 'keyCommon', isException: false, exeptionStyle: {} },
            { key: 'return', moreSymbol: [], sound: 'keyException.mp3', style: 'keyException', isException: true, exeptionStyle: {} },
        ],
    ],
};
